### ISSUE TITLE
Discussion for new feature: show when lap mode is activated

### ISSUE THREAD

**Issue by timrichardson** [gistart/tp_wattmeter#16]
Hi, modern thinkpads enter 'lap mode' when movement of the device is discussed. After a period of no movement, lap mode is deactived. This seems to take about five minutes at the fastest. Lap mode can be triggered with even slight movement, such as moving the laptop while it is on the desk. 

When lap mode is activated, thermal throttling is quite severe. I have tested it on a Tigerlake X1 and Yoga; throttling caps CPU temp at 65 C, but in performance mode it should be 95C.

Gnome power settings will show when lap mode is activated, but it is annoying to check.
It's a good for an extension with an indicator, such as tp_wattmeter. It is not related to power consumption, but it is related to ThinkPads. 

Would a pull request for this be accepted? Otherwise I will work on a stand-alone extension. I propose to use capital letter L to indicate when lap mode is detected, and nothing if not detected.

Detection of lap mode is done by inspecting /sys/devices/platform/thinkpad_acpi/dytc_lapmode
which has a value of 1 or 0.  The polling period of the existing extension will be fine.

**Comment by gistart** [comment]
Hi, sure I'll accept PR for this feature. Thank you!

**Comment by timrichardson** [comment]
pr #17

**Comment by timrichardson** [comment]
is there anything you want me to change in the PR?

**Comment by gistart** [comment]
I removed new version from metadata, let it keep incrementing from previous numbers

Sorry it took so long, rough times out here
